name: conditions
on: [ workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello"

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}  # We use if for condition, should be before run
        run: echo "Deploying..."