name: conditions  # workflow name
on: [push]  # event

jobs:    #stages
  confition:   # stage name
   runs-on: ubuntu-latest  #agent name
   steps:   #steps in jenkins inside stage (list of map)
   - name: deploy
     if: github.ref == 'refs/heads/main'
     run: echo "deploy"
  
   - name: UAT
     run: echo "uat"