name: hello pipeline  #workflow name
on:  # Event
# on: [ push ]
 push:
  branches: [ main ]

jobs:  #Workflow can have multiple jobs
  hello:  # job name
   runs-on: ubuntu-latest  #agents

   steps:
   - name: say hello
     run: echo "Hello world"