name: hello workflow  # name of the workflow
on: [ workflow_dispatch ] #event

jobs: #stages. workflow can have multiple stage
  hello:  #name of the job/stage
   runs-on: ubuntu-latest  #Runner to execute the job/stage

   steps:  
   - name: say hello
     run: echo "hell,world"

  bolo:
   runs-on: ubuntu-latest
   steps:
   - name: chakra
     run: echo "hello chakra"