## Name of the workflow?
name: inputs

## How to tigger?
on: 
  workflow_dispatch:  # Says to trigger manually passing inputs 2be defined
   inputs:
     name:
      type: string
      default: "Chakradhar"
      required: true
      description: "enter your name"
     
     environment:
      type: environment
      required: true
      description: "select environment"

     version:
      type: choice
      required: true
      description: "select version"
      default: v1
      options: 
      - v1
      - v2
      - v3

     deploy:
       description: "do you want to deploy"
       type: boolean
       required: true
       default: false

## defines jobs to run
jobs: 
  inputs:   # name of the job
   runs-on: ubuntu-latest

   # define steps to execute
   steps:
   - name: display inputs
     run: |
       echo "name: ${{ inputs.name }}"
       echo "environment: ${{ inputs.environment }}"  
       echo "version: ${{ inputs.version }}"
       echo "Deploy: ${{inputs.deploy }}"