# name of the workflow
name: options
# tigger mechanisum
on: [workflow_dispatch]

#In workflow, to prevent concurrent triggers we use groups
concurrency:
 group: ${{ github.repository }}-$${{ github.ref }}
 cancel-in-progress: true

#what to run?
jobs:
  options:  #name of the job
  # where the job should run?
   runs-on: ubuntu-latest
   timeout-minutes: 1   # timeout is set for the whole job, like whole pipeline in jenkins
   # we can set step level in jenkins and workflow

   steps: # Tasks to be executed, its a list object
   - name: sleep
     run: sleep 1000
