name: dependency
on: [workflow_dispatch]
 inputs:
   deploy:
    description: 'do you want to deploy'
    required: true
    default: false
    type: boolean

jobs:
 job-1:
  runs-on: ubuntu-latest
  steps:
  - name: print myname
    run: echo "chakradhar"
 job-2:
  needs: job-1
  if: inputs.deploy
  runs-on: ubuntu-latest
  steps:
  - name: print myname
    run: echo "chakradhar"
 job-3:
  runs-on: ubuntu-latest
  steps:
  - name: print myname
    run: echo "chakradhar"
 job-4:
  needs: job-2
  runs-on: ubuntu-latest
  steps:
  - name: print myname
    run: echo "chakradhar"
    