name: parallel-default
on: [ workflow_dispatch ]

jobs:
 jobs-1:
  runs-on: ubuntu-latest
  steps:
    - name: deploy
      run: echo "deploy jobs-1"
  
 jobs-2:
  needs: jobs-1
  runs-on: ubuntu-latest
  steps:
    - name: deploy
      run: echo "deploy jobs-2"

 jobs-3:
  runs-on: ubuntu-latest
  steps:
    - name: deploy
      run: echo "deploy jobs-3"

 jobs-4:
  needs: jobs-3
  runs-on: ubuntu-latest
  steps:
    - name: deploy
      run: echo "deploy jobs-4"