name: post
on: [ workflow_dispatch ]

jobs:
 post:
  runs-on: ubuntu-latest
  steps:
  - name: print name
    run: exit 1
  
  - name: success
    if: ${{ success() }}
    run: echo "Previous step was successful"
  
  - name: failure
    if: ${{ failure() }}
    run: echo " Previous step failed"

  - name: always
    if: ${{ always() }}
    run: echo "run regardless of result"

  - name: cancelled
    if: ${{ cancelled() }}
    run: echo "Previous step was cancelled"